# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-09 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deniishere',
            name='exam',
        ),
        migrations.AddField(
            model_name='fib_plus_question',
            name='answer1',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='fib_plus_question',
            name='answer2',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='fib_plus_question',
            name='answer3',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='fib_plus_question',
            name='answer4',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='fib_plus_question',
            name='answer5',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer1',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer10',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer11',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer12',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer13',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer14',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer15',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer16',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer17',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer18',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer19',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer2',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer20',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer3',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer4',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer5',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer6',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer7',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer8',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer9',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='num_question',
            name='answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer1',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer10',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer11',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer12',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer13',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer14',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer15',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer16',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer17',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer18',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer19',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer2',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer20',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer3',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer4',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer5',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer6',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer7',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer8',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer9',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='sr_question',
            name='answer',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='num_question',
            name='question',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sr_question',
            name='question',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='DeniIsHere',
        ),
    ]
