# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIB_SINGLE_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=600)),
                ('x', models.CharField(default=b'null', max_length=600)),
            ],
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer10',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer11',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer12',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer13',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer14',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer15',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer16',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer17',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer18',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer19',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer20',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer5',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer6',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer7',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer8',
        ),
        migrations.RemoveField(
            model_name='ma_question',
            name='answer9',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer10',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer11',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer12',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer13',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer14',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer15',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer16',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer17',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer18',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer19',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer20',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer5',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer6',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer7',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer8',
        ),
        migrations.RemoveField(
            model_name='mc_question',
            name='answer9',
        ),
        migrations.AddField(
            model_name='fib_plus_question',
            name='x',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='fib_plus_question',
            name='y',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='fib_plus_question',
            name='z',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='A',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='B',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='C',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='D',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='E',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='F',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='G',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='H',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='I',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='J',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='K',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='L',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='M',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='N',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='O',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='P',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='Q',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='R',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='S',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ma_question',
            name='T',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='A',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='B',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='C',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='D',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='E',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='F',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='G',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='H',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='I',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='J',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='K',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='L',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='M',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='N',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='O',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='P',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='Q',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='R',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='S',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='T',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer1',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer10',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer11',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer12',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer13',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer14',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer15',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer16',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer17',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer18',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer19',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer2',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer20',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer3',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer4',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer5',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer6',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer7',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer8',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mat_question',
            name='answer9',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='A',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='B',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='C',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='D',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='E',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='F',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='G',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='H',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='I',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='J',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='K',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='L',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='M',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='N',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='O',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='P',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='Q',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='R',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='S',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='mc_question',
            name='T',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='num_question',
            name='answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer1',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer10',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer11',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer12',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer13',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer14',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer15',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer16',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer17',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer18',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer19',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer2',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer20',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer3',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer4',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer5',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer6',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer7',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer8',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='ord_question',
            name='answer9',
            field=models.CharField(default=b'null', max_length=600),
        ),
        migrations.AddField(
            model_name='sr_question',
            name='answer',
            field=models.TextField(default=b'null'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text=b'Enter the CourseID (e.g. Artificial Intelligence)', max_length=600),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text=b"Enter the Department's name (e.g. Computer Science)", max_length=200),
        ),
        migrations.AlterField(
            model_name='ess_question',
            name='question',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='exam',
            name='InstrucorName',
            field=models.CharField(help_text=b'Enter Instructors name (e.g. Sertac Artan)', max_length=600),
        ),
        migrations.AlterField(
            model_name='exam',
            name='InstructorsEmail',
            field=models.EmailField(help_text=b'Enter Instructors email (e.g. dshakhbu@nyit.edu)', max_length=600),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Year',
            field=models.CharField(help_text=b'Enter the Year (e.g. 2017)', max_length=600),
        ),
        migrations.AlterField(
            model_name='fib_plus_question',
            name='question',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='mat_question',
            name='question',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='num_question',
            name='question',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='ord_question',
            name='question',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='sr_question',
            name='question',
            field=models.CharField(max_length=600),
        ),
        migrations.AddField(
            model_name='fib_single_question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Exam'),
        ),
    ]
