# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20171212_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='ord_question',
            name='correct',
            field=models.CharField(default=20, help_text=b'enter the correct order', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tf_question',
            name='answers',
            field=models.CharField(blank=True, choices=[(b'True', b'True'), (b'False', b'False')], default=b'null', max_length=5),
        ),
    ]
