# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171214_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='mat_question',
            name='correct',
            field=models.CharField(default=20, help_text=b'enter the correct match, in format number-letter, etc', max_length=600),
            preserve_default=False,
        ),
    ]
