# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171212_0032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FIB_Question',
            new_name='FIB_SINGLE_Question',
        ),
    ]
