# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-04 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20171204_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='college',
        ),
        migrations.AddField(
            model_name='school',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.College'),
        ),
    ]
