# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-05 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20171204_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='DepartmentName',
        ),
        migrations.AddField(
            model_name='course',
            name='DepartmentName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Department'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='department',
            name='SchoolName',
        ),
        migrations.AddField(
            model_name='department',
            name='SchoolName',
            field=models.ForeignKey(default=1, help_text='Select a School for this Department', on_delete=django.db.models.deletion.CASCADE, to='catalog.School'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Course',
        ),
        migrations.AddField(
            model_name='exam',
            name='Course',
            field=models.ForeignKey(default=1, help_text='Select a Course for this Exam', on_delete=django.db.models.deletion.CASCADE, to='catalog.Course'),
            preserve_default=False,
        ),
    ]
