# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-05 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20171205_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESS_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FIB_PLUS_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MA_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MAT_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MC_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NUM_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ORD_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Essay_Question', models.ManyToManyField(help_text='Essay Questions', to='catalog.ESS_Question')),
                ('Fill_in_blank_Question', models.ManyToManyField(help_text='Fill in the Blank Questions', to='catalog.FIB_PLUS_Question')),
                ('Match_Question', models.ManyToManyField(help_text='Matching Questions', to='catalog.MAT_Question')),
                ('Multuple_Answer_Question', models.ManyToManyField(help_text='Multuple Answer Questions', to='catalog.MA_Question')),
                ('Multuple_Choice_Question', models.ManyToManyField(help_text='Multuple Choice Questions', to='catalog.MC_Question')),
                ('Numeric_Reponse_Question', models.ManyToManyField(help_text='Number Response  Questions', to='catalog.NUM_Question')),
                ('Order_Question', models.ManyToManyField(help_text='Ordering Questions', to='catalog.ORD_Question')),
            ],
        ),
        migrations.CreateModel(
            name='SR_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TF_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answers', models.CharField(blank=True, choices=[('t', 'True'), ('f', 'False')], default='f', help_text='Semester', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='questiontypes',
            name='Short_Reponse_Question',
            field=models.ManyToManyField(help_text='Multuple Choice Questions', to='catalog.SR_Question'),
        ),
        migrations.AddField(
            model_name='questiontypes',
            name='True_or_False_Question',
            field=models.ManyToManyField(help_text='True or False Questions', to='catalog.TF_Question'),
        ),
    ]
