# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-05 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20171205_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontypes',
            name='exam',
            field=models.ForeignKey(default=1, help_text='Exam', on_delete=django.db.models.deletion.CASCADE, to='catalog.Exam'),
            preserve_default=False,
        ),
    ]
